### ISSUE TITLE
내배캠 안드로이드 앱개발 심화 개인과제 피드백

### ISSUE THREAD

**Issue by tutorhwang** [Jisung15/ImageSearchApp#1]
### 총평
안녕하세요! 누구보다 성실한 성진님!!
오늘 리드미가 환상적이네요!

viewModel은 벌써 익숙해지면 안되죠! 반복!! 반복입니다!
null 처리는 10년 뒤에도 고민하게 되는 부분이예요. 계속 고민하세요!!!
무한 스크롤은 잘 해내었어요 한번만 완성하고 나면 복붙 기능이죠!
즐겨찾기는 보관함에 저장후 사실 검색 page에서도 update하라는 요구사항은 없어요.
이부분은 한땀 한땀 구현은 가능한데.. 이건 같이 고민해봅시다!
API 키를 하드코딩해서 깃허브에 올리면 보안 경고메일이 올거예요.
돈과 보완과 관련된 부분이라 그렇죠!
local.properties에 저장하는 방법을 한번 찾아보세요!

나머지는 튜터룸으로!!

### 코드 피드백
https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/dataClass/SearchData.kt#L6C4-L16
Retrofit 용이 아니면 @SerializedName 어노테이션 삭제하시면  됩니다!

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/fragment/BookMarkFragment.kt#L20
shareViewModel 잘 활용했네요!
https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/fragment/BookMarkFragment.kt#L40-L42
observe도 잘 작성했네요!

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/fragment/SearchFragment.kt#L122
키는 local.properties에 저장해서 감춰보세요!

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/retrofit/RetrofitInterface.kt#L12-L26
변하지 않는 값은 미리 default 값을 추가해 둬도 좋아요.
```
    suspend fun getImage(
        @Header("Authorization") apiKey: String,
        @Query("query") query: String,
        @Query("sort") sort: String = "recent",
        @Query("page") page: Int = 1,
        @Query("size") size: Int
```

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/fragment/SearchFragment.kt#L121-L135
data쪽 코드는 추후 MVVM 적용시 Repository로 옮겨지면 됩니다.

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/fragment/SearchFragment.kt#L119
loading은 MVVM 적용시 UIState를 활용해서 구현해 보세요. 훨씬 코드 가독성이 좋아집니다.

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/fragment/SearchFragment.kt#L121-L136
두가지 작업이 순차적으로 적용되는 코드를 async와 await을 활용하면 두가지 작업을 동시에 할 수 있게 됩니다. async를 활용해 보세요.!
```
    lifecycleScope.launch {
        try {
            // async를 사용하여 네트워크 요청을 병렬로 실행
            val imageDeferred = async {
                RetrofitClient.makeRetrofit.getImage(
                    apiKey = "KakaoAK d9e31c60db2fd236337a605b8b0128bf",
                    query = query,
                    sort = "recency",
                    page = page,
                    size = 50
                )
            }

            val videoDeferred = async {
                RetrofitClient.makeRetrofit.getVideo(
                    apiKey = "KakaoAK d9e31c60db2fd236337a605b8b0128bf",
                    query = query,
                    sort = "recency",
                    page = page,
                    size = 30
                )
            }

            // 두 요청이 모두 완료될 때까지 기다린 후 결과를 가져옴
            val imageResponseData = imageDeferred.await()
            val videoResponseData = videoDeferred.await()

```

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/recyclerView/SearchRecyclerViewAdapter.kt#L16
List관리에 최적화 된 ListAdapter도 활용해보세요!

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/viewModel/BookMarkViewModel.kt#L10
잘 이해하고 있군요!
두 Fragment에서 공유해야하기에 activityViewModels를 활용하며 좋겠죠?

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/MainActivity.kt#L31
@SuppressLint 어노테이션을 사용하기 보다 호환성 있는 함수로 변환해주면 좋아요.
```
        TabLayoutMediator(tabLayout, viewPager) { tab, position ->
            tab.text = items[position]
            tab.icon = when (position) {
                0 -> ContextCompat.getDrawable(this@MainActivity, R.drawable.home)
                else -> ContextCompat.getDrawable(this@MainActivity, R.drawable.choice_icon)
            }
```

https://github.com/Jisung15/ImageSearchApp/blob/7e70fb75c2e15b13f9e3af85e5a26d73e3f40a8e/app/src/main/java/com/example/imagesearchapp/checkList#L51-L56
sharedPreference만 완성하면 되는군요! MVVM 패턴과 sharedPreference 에 대해서 반복 연습해봅시다!

**Comment by Jisung15** [comment]
async 쓰려다가 어려워서 못 썼어요.. ㅋㅋ
